server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG
          jwt: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          adeo:
            client-id: ${OAUTH2_ADEO_CLIENT_ID}
            client-secret: ${OAUTH2_ADEO_SECRET_ID}
            scope:
              - openid
              - email
              - profile
              - groups
              - advprofile
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            #redirect-uri-template: http://localhost:9006/login/oauth2/code/adeo
        provider:
          adeo:
            token-uri: ${OAUTH2_ADEO_TOKEN_URI}
            authorization-uri: ${OAUTH2_ADEO_AUTHORIZATION_URI}
            user-info-uri: ${OAUTH2_ADEO_USER_INFO_URI}
            user-name-attribute: ${OAUTH2_ADEO_USER_NAME_ATTRIBUTE}
            issuer-uri: ${OAUTH2_ADEO_ISSUER_URI}
            jwk-set-uri: ${OAUTH2_ADEO_JWK_SET_URI}
